apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lm-tenant-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lm-tenant-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lm-controller
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: lm-controller
  name: lm-leader-election-rolebinding
  namespace: weave-ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lm-leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
