apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: llm-ui
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: llm-ui
  namespace: default
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: llm-ui